// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: notes/notes.proto

package notes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_notes_notes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_notes_notes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_notes_notes_proto_rawDescGZIP(), []int{0}
}

func (x *Note) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FetchByTitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchByTitle) Reset() {
	*x = FetchByTitle{}
	mi := &file_notes_notes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchByTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchByTitle) ProtoMessage() {}

func (x *FetchByTitle) ProtoReflect() protoreflect.Message {
	mi := &file_notes_notes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchByTitle.ProtoReflect.Descriptor instead.
func (*FetchByTitle) Descriptor() ([]byte, []int) {
	return file_notes_notes_proto_rawDescGZIP(), []int{1}
}

func (x *FetchByTitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListTitlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titles        []string               `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTitlesResponse) Reset() {
	*x = ListTitlesResponse{}
	mi := &file_notes_notes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTitlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTitlesResponse) ProtoMessage() {}

func (x *ListTitlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_notes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTitlesResponse.ProtoReflect.Descriptor instead.
func (*ListTitlesResponse) Descriptor() ([]byte, []int) {
	return file_notes_notes_proto_rawDescGZIP(), []int{2}
}

func (x *ListTitlesResponse) GetTitles() []string {
	if x != nil {
		return x.Titles
	}
	return nil
}

type ListTitles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTitles) Reset() {
	*x = ListTitles{}
	mi := &file_notes_notes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTitles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTitles) ProtoMessage() {}

func (x *ListTitles) ProtoReflect() protoreflect.Message {
	mi := &file_notes_notes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTitles.ProtoReflect.Descriptor instead.
func (*ListTitles) Descriptor() ([]byte, []int) {
	return file_notes_notes_proto_rawDescGZIP(), []int{3}
}

type ListNotes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotes) Reset() {
	*x = ListNotes{}
	mi := &file_notes_notes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotes) ProtoMessage() {}

func (x *ListNotes) ProtoReflect() protoreflect.Message {
	mi := &file_notes_notes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotes.ProtoReflect.Descriptor instead.
func (*ListNotes) Descriptor() ([]byte, []int) {
	return file_notes_notes_proto_rawDescGZIP(), []int{4}
}

type AllNotes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllNotes) Reset() {
	*x = AllNotes{}
	mi := &file_notes_notes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNotes) ProtoMessage() {}

func (x *AllNotes) ProtoReflect() protoreflect.Message {
	mi := &file_notes_notes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNotes.ProtoReflect.Descriptor instead.
func (*AllNotes) Descriptor() ([]byte, []int) {
	return file_notes_notes_proto_rawDescGZIP(), []int{5}
}

func (x *AllNotes) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

var File_notes_notes_proto protoreflect.FileDescriptor

const file_notes_notes_proto_rawDesc = "" +
	"\n" +
	"\x11notes/notes.proto\x12\x05notes\"J\n" +
	"\x04Note\x12\x12\n" +
	"\x04Date\x18\x01 \x01(\tR\x04Date\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\"$\n" +
	"\fFetchByTitle\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\",\n" +
	"\x12ListTitlesResponse\x12\x16\n" +
	"\x06titles\x18\x01 \x03(\tR\x06titles\"\f\n" +
	"\n" +
	"ListTitles\"\v\n" +
	"\tListNotes\"-\n" +
	"\bAllNotes\x12!\n" +
	"\x05notes\x18\x01 \x03(\v2\v.notes.NoteR\x05notes2\xdc\x01\n" +
	"\vNoteRequest\x12+\n" +
	"\aGetNote\x12\x13.notes.FetchByTitle\x1a\v.notes.Note\x12.\n" +
	"\n" +
	"CreateNote\x12\v.notes.Note\x1a\x13.notes.FetchByTitle\x12=\n" +
	"\rListAllTitles\x12\x11.notes.ListTitles\x1a\x19.notes.ListTitlesResponse\x121\n" +
	"\fListAllNotes\x12\x10.notes.ListNotes\x1a\x0f.notes.AllNotesB\bZ\x06/notesb\x06proto3"

var (
	file_notes_notes_proto_rawDescOnce sync.Once
	file_notes_notes_proto_rawDescData []byte
)

func file_notes_notes_proto_rawDescGZIP() []byte {
	file_notes_notes_proto_rawDescOnce.Do(func() {
		file_notes_notes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notes_notes_proto_rawDesc), len(file_notes_notes_proto_rawDesc)))
	})
	return file_notes_notes_proto_rawDescData
}

var file_notes_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notes_notes_proto_goTypes = []any{
	(*Note)(nil),               // 0: notes.Note
	(*FetchByTitle)(nil),       // 1: notes.FetchByTitle
	(*ListTitlesResponse)(nil), // 2: notes.ListTitlesResponse
	(*ListTitles)(nil),         // 3: notes.ListTitles
	(*ListNotes)(nil),          // 4: notes.ListNotes
	(*AllNotes)(nil),           // 5: notes.AllNotes
}
var file_notes_notes_proto_depIdxs = []int32{
	0, // 0: notes.AllNotes.notes:type_name -> notes.Note
	1, // 1: notes.NoteRequest.GetNote:input_type -> notes.FetchByTitle
	0, // 2: notes.NoteRequest.CreateNote:input_type -> notes.Note
	3, // 3: notes.NoteRequest.ListAllTitles:input_type -> notes.ListTitles
	4, // 4: notes.NoteRequest.ListAllNotes:input_type -> notes.ListNotes
	0, // 5: notes.NoteRequest.GetNote:output_type -> notes.Note
	1, // 6: notes.NoteRequest.CreateNote:output_type -> notes.FetchByTitle
	2, // 7: notes.NoteRequest.ListAllTitles:output_type -> notes.ListTitlesResponse
	5, // 8: notes.NoteRequest.ListAllNotes:output_type -> notes.AllNotes
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notes_notes_proto_init() }
func file_notes_notes_proto_init() {
	if File_notes_notes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notes_notes_proto_rawDesc), len(file_notes_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notes_notes_proto_goTypes,
		DependencyIndexes: file_notes_notes_proto_depIdxs,
		MessageInfos:      file_notes_notes_proto_msgTypes,
	}.Build()
	File_notes_notes_proto = out.File
	file_notes_notes_proto_goTypes = nil
	file_notes_notes_proto_depIdxs = nil
}
