// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: notes/notes.proto

package notes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteRequest_GetNote_FullMethodName       = "/notes.NoteRequest/GetNote"
	NoteRequest_CreateNote_FullMethodName    = "/notes.NoteRequest/CreateNote"
	NoteRequest_ListAllTitles_FullMethodName = "/notes.NoteRequest/ListAllTitles"
	NoteRequest_ListAllNotes_FullMethodName  = "/notes.NoteRequest/ListAllNotes"
)

// NoteRequestClient is the client API for NoteRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteRequestClient interface {
	GetNote(ctx context.Context, in *FetchByTitle, opts ...grpc.CallOption) (*Note, error)
	CreateNote(ctx context.Context, in *Note, opts ...grpc.CallOption) (*FetchByTitle, error)
	ListAllTitles(ctx context.Context, in *ListTitles, opts ...grpc.CallOption) (*ListTitlesResponse, error)
	ListAllNotes(ctx context.Context, in *ListNotes, opts ...grpc.CallOption) (*AllNotes, error)
}

type noteRequestClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteRequestClient(cc grpc.ClientConnInterface) NoteRequestClient {
	return &noteRequestClient{cc}
}

func (c *noteRequestClient) GetNote(ctx context.Context, in *FetchByTitle, opts ...grpc.CallOption) (*Note, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Note)
	err := c.cc.Invoke(ctx, NoteRequest_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteRequestClient) CreateNote(ctx context.Context, in *Note, opts ...grpc.CallOption) (*FetchByTitle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchByTitle)
	err := c.cc.Invoke(ctx, NoteRequest_CreateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteRequestClient) ListAllTitles(ctx context.Context, in *ListTitles, opts ...grpc.CallOption) (*ListTitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTitlesResponse)
	err := c.cc.Invoke(ctx, NoteRequest_ListAllTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteRequestClient) ListAllNotes(ctx context.Context, in *ListNotes, opts ...grpc.CallOption) (*AllNotes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllNotes)
	err := c.cc.Invoke(ctx, NoteRequest_ListAllNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteRequestServer is the server API for NoteRequest service.
// All implementations must embed UnimplementedNoteRequestServer
// for forward compatibility.
type NoteRequestServer interface {
	GetNote(context.Context, *FetchByTitle) (*Note, error)
	CreateNote(context.Context, *Note) (*FetchByTitle, error)
	ListAllTitles(context.Context, *ListTitles) (*ListTitlesResponse, error)
	ListAllNotes(context.Context, *ListNotes) (*AllNotes, error)
	mustEmbedUnimplementedNoteRequestServer()
}

// UnimplementedNoteRequestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteRequestServer struct{}

func (UnimplementedNoteRequestServer) GetNote(context.Context, *FetchByTitle) (*Note, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedNoteRequestServer) CreateNote(context.Context, *Note) (*FetchByTitle, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedNoteRequestServer) ListAllTitles(context.Context, *ListTitles) (*ListTitlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllTitles not implemented")
}
func (UnimplementedNoteRequestServer) ListAllNotes(context.Context, *ListNotes) (*AllNotes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllNotes not implemented")
}
func (UnimplementedNoteRequestServer) mustEmbedUnimplementedNoteRequestServer() {}
func (UnimplementedNoteRequestServer) testEmbeddedByValue()                     {}

// UnsafeNoteRequestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteRequestServer will
// result in compilation errors.
type UnsafeNoteRequestServer interface {
	mustEmbedUnimplementedNoteRequestServer()
}

func RegisterNoteRequestServer(s grpc.ServiceRegistrar, srv NoteRequestServer) {
	// If the following call panics, it indicates UnimplementedNoteRequestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteRequest_ServiceDesc, srv)
}

func _NoteRequest_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchByTitle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteRequestServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteRequest_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteRequestServer).GetNote(ctx, req.(*FetchByTitle))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteRequest_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteRequestServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteRequest_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteRequestServer).CreateNote(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteRequest_ListAllTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTitles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteRequestServer).ListAllTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteRequest_ListAllTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteRequestServer).ListAllTitles(ctx, req.(*ListTitles))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteRequest_ListAllNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteRequestServer).ListAllNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteRequest_ListAllNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteRequestServer).ListAllNotes(ctx, req.(*ListNotes))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteRequest_ServiceDesc is the grpc.ServiceDesc for NoteRequest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteRequest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notes.NoteRequest",
	HandlerType: (*NoteRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _NoteRequest_GetNote_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _NoteRequest_CreateNote_Handler,
		},
		{
			MethodName: "ListAllTitles",
			Handler:    _NoteRequest_ListAllTitles_Handler,
		},
		{
			MethodName: "ListAllNotes",
			Handler:    _NoteRequest_ListAllNotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notes/notes.proto",
}
